### ISSUE TITLE
Bluesky web client

### ISSUE THREAD

**Issue by cryos** [NSLS-II/project-management#11]
Create a web client that can make calls to the [Bluesky Queue Server](https://github.com/bluesky/bluesky-queueserver/)

- [x] Create basic web application repository with starting point
- [x] Add button that calls RESTful API to "add to queue"
- [x] Offer a list of plans that can be selected to submit
- [x] Create editable field(s) that have defaults, can be changed before "adding to queue"
- [ ] Display the scan id / UID for the scan, report success/failure

**Comment by cryos** [comment]
We should try to coordinate with #20 where reasonable/possible.

**Comment by cryos** [comment]
I created the repo at https://github.com/bluesky/bluesky-webclient

**Comment by mrakitin** [comment]
Thank you, @cryos!

**Comment by cryos** [comment]
https://github.com/bluesky/bluesky-webclient/pull/1 adds the button, many more buttons to add after this. The layout/presentation needs work too, but I think this is headed in the right direction.

**Comment by cryos** [comment]
Deferring on the scan id/UID for a future epic, all core goals are present in the client at this point, and combined withe the databroker client we can show UIDs for scans done in the demo system.
