### ISSUE TITLE
Web client for databroker

### ISSUE THREAD

**Issue by cryos** [NSLS-II/project-management#20]
Develop a prototype for a databroker web client

- [x] Show available catalogs on the server
- [x] Show runs within catalogs
- [x] Display thumbnails of the runs in the catalogs
- [x] Show run metadata
- [ ] Implement basic search capabilities

**Comment by cryos** [comment]
High level summary I am using TypeScript with React and Material-UI to flesh out a single page application using the react router to reflect current content in the browsers address bar. I am fleshing out a minimal example hitting the databroker server APIs.

**Comment by mrakitin** [comment]
Where is the db web client code living?

**Comment by cryos** [comment]
I need to get it pushed, so just local right now, I can create a repository and get it pushed.

**Comment by cryos** [comment]
I created and pushed to https://github.com/bluesky/databroker-client

**Comment by mrakitin** [comment]
Thanks, @cryos!

**Comment by cryos** [comment]
![image](https://user-images.githubusercontent.com/42214/93258499-661e1e80-f76c-11ea-9479-1cfe8a406fbf.png)
Basic thumbnailing is working locally, just cleaning things up but will get this into the repositories shortly. It is still hack-ish, and very much at the MVP level, but hopefully shows the basics in a more visual way. I have added [client](https://github.com/bluesky/databroker-client/pull/1) and [server](https://github.com/bluesky/databroker-server/pull/1) pull requests for the image previews, they currently rely on pre-generated PNGs.

**Comment by cryos** [comment]
For search I think it would be good to get more sample data, and come up with some things that we should offer search on. This iteration is very much focused on a minimal implementation upon which we can build, can we get something in a standard search box, or do we need a dedicated form with some entries?

**Comment by cryos** [comment]
Pushing basic search to a future effort, the client is already functional for a minimum viable product, and enables us to see data moved from acquisition to analysis pods in the bluesky-pods demonstration.
