### ISSUE TITLE
Operational schedule API

### ISSUE THREAD

**Issue by cryos** [NSLS-II/project-management#24]
Expose the facility operational schedule through an API.

Expected to be used to display facility operational status when, for example, selecting a session to view in the databroker client

- [x] Get facility status by month

- [x] Get facility status by day

- [x]  Get facility status by shift

**Comment by mrakitin** [comment]
I hope we won't have to parse this png/pdf: https://www.bnl.gov/ps/nsls2/opschedule.php.

**Comment by JunAishima** [comment]
one quick reminder, the CryoEM facility does not require beam so can operate outside of the normal operational schedule - I need to ask what they're planning on doing!

**Comment by JunAishima** [comment]
where is this API meant to be used?

**Comment by cryos** [comment]
I think this needs sketching out more, but having an API  for the schedule would then enable pages to display relevant schedule dynamically.
