### ISSUE TITLE
Resource API

### ISSUE THREAD

**Issue by cryos** [NSLS-II/project-management#25]
Expose operational resources:

- [x] Instruments (Beamlines)
- [x] Sample environments

Basically anything that needs scheduling

**Comment by JunAishima** [comment]
is this API aimed to be used during the process of the user selecting available plans?

**Comment by cryos** [comment]
My understanding was that the API enables you to get beamline information, that may extend all the way to plans, but I was thinking of name, location, point of contact, available sample environments, etc. So more static, but it might extend to plans if they are more static.

**Comment by JunAishima** [comment]
As shown on the [API document](https://brookhavenlab.sharepoint.com/:w:/r/sites/DAMA/_layouts/15/Doc.aspx?sourcedoc=%7B943519b5-eff6-4311-b829-216d7a7fc1e7%7D&action=edit&wdPid=157fe532&cid=c156c494-177b-4488-a87a-b71999d19d48), this has been implemented as two separate endpoints, instruments, and resources. Only very basic information has been put in for now.
